name: auth_google_package
description: Package para autenticação de usuario usando as apis do Google.
version: 1.2.3
homepage: https://github.com/pwlimaverde/auth_google_package

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  return_success_or_error: ^0.1.7
  flutter:
    sdk: flutter

dev_dependencies:
  rxdart: ^0.26.0
  mocktail: ^0.0.1-dev.10
  flutter_test:
    sdk: flutter
    
flutter: